@startuml
'https://plantuml.com/class-diagram

class Numero {
-double real
-double imaginary
+ComplexNumber(double real, double imaginary)
+ComplexNumber(double real)
+double getReal()
+double getImaginary()
+ComplexPlus(Complex c)
}

@enduml